[package]
name = "ticket-verification"
version = "0.1.7"
edition = "2021"
license = "BUSL-1.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13.0"
borsh = "0.9.3"
bs58 = "0.4.0"
eyre = "0.6.8"
solana-sdk = "1.11.10"
thiserror = "1.0.33"
common-data = { git = "https://github.com/ticketland-io/common-rust", version = "0.3.36" }
program-artifacts = { git = "https://github.com/ticketland-io/program-artifacts", version = "0.1.24" }
ticketland-core = { git = "https://github.com/ticketland-io/common-rust", version = "0.2.13"  }
solana-web3-rust = { git = "https://github.com/ticketland-io/solana-web3-rust", version = "0.1.9" }
ticketland-crypto = { git = "https://github.com/ticketland-io/common-rust", version = "0.1.14" }
serde = "1.0"
